# Generated by Django 5.1.4 on 2025-01-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.JSONField()),
                ('nSol', models.IntegerField()),
                ('minSol', models.IntegerField()),
                ('solution', models.JSONField()),
                ('recordTime', models.TimeField(default='00:00:00')),
                ('recordMoves', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('nWidth', models.IntegerField()),
                ('expantionFactor', models.FloatField()),
                ('enemyFactor', models.FloatField()),
                ('blockFactor', models.FloatField()),
                ('nPop', models.IntegerField()),
                ('mutationFactor', models.FloatField()),
                ('maxIter', models.IntegerField()),
                ('maxMoves', models.IntegerField()),
            ],
        ),
    ]
