# Generated by Django 5.1.4 on 2025-01-11 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdgpuzzleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='petitionManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dungeonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdgpuzzleapp.dungeondata')),
                ('petitionData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdgpuzzleapp.dungeonpetition')),
            ],
        ),
    ]
