# Generated by Django 5.1.4 on 2025-01-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdgpuzzleapp', '0002_petitionmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitionmanager',
            name='status',
        ),
        migrations.AddField(
            model_name='dungeondata',
            name='solutionPlayer',
            field=models.JSONField(default='[]'),
        ),
    ]
