# Generated by Django 5.1.5 on 2025-01-28 02:30

import puzzleapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dungeondata',
            old_name='minSol',
            new_name='min_sol',
        ),
        migrations.RenameField(
            model_name='dungeondata',
            old_name='nSol',
            new_name='n_sol',
        ),
        migrations.RenameField(
            model_name='dungeondata',
            old_name='recordMoves',
            new_name='record_moves',
        ),
        migrations.RenameField(
            model_name='dungeondata',
            old_name='recordTime',
            new_name='record_time',
        ),
        migrations.RenameField(
            model_name='petitionmanager',
            old_name='dungeonId',
            new_name='dungeon_id',
        ),
        migrations.RenameField(
            model_name='petitionmanager',
            old_name='petitionData',
            new_name='petition_data',
        ),
        migrations.RenameField(
            model_name='petitionmanager',
            old_name='statusP',
            new_name='status_p',
        ),
        migrations.RenameField(
            model_name='petitionmanager',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='blockFactor',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='enemyFactor',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='expantionFactor',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='maxIter',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='maxMoves',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='mutationFactor',
        ),
        migrations.RemoveField(
            model_name='datapetition',
            name='nPop',
        ),
        migrations.RemoveField(
            model_name='dungeondata',
            name='solutionPlayer',
        ),
        migrations.AddField(
            model_name='datapetition',
            name='block_factor',
            field=models.FloatField(default=0.1, validators=[puzzleapi.validators.validate_block_factor]),
        ),
        migrations.AddField(
            model_name='datapetition',
            name='enemy_factor',
            field=models.FloatField(default=0.083, validators=[puzzleapi.validators.validate_enemy_factor]),
        ),
        migrations.AddField(
            model_name='datapetition',
            name='expantion_factor',
            field=models.FloatField(default=0.1, validators=[puzzleapi.validators.validate_expantion_factor]),
        ),
        migrations.AddField(
            model_name='datapetition',
            name='max_iter',
            field=models.IntegerField(default=20, validators=[puzzleapi.validators.validate_max_iter]),
        ),
        migrations.AddField(
            model_name='datapetition',
            name='max_moves',
            field=models.IntegerField(default=0.5, validators=[puzzleapi.validators.validate_max_moves]),
        ),
        migrations.AddField(
            model_name='datapetition',
            name='mutation_factor',
            field=models.FloatField(default=12, validators=[puzzleapi.validators.validate_mutation_factor]),
        ),
        migrations.AddField(
            model_name='datapetition',
            name='n_pop',
            field=models.IntegerField(default=12, validators=[puzzleapi.validators.validate_n_pop]),
        ),
        migrations.AddField(
            model_name='dungeondata',
            name='solution_player',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='datapetition',
            name='height',
            field=models.IntegerField(default=7, validators=[puzzleapi.validators.validate_height]),
        ),
        migrations.AlterField(
            model_name='datapetition',
            name='nWidth',
            field=models.IntegerField(default=7, validators=[puzzleapi.validators.validate_nWidth]),
        ),
    ]
