# Generated by Django 5.1.5 on 2025-01-28 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleapi', '0002_rename_minsol_dungeondata_min_sol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeondata',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petitionmanager',
            name='dungeon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzleapi.dungeondata'),
        ),
    ]
