# Generated by Django 5.1.5 on 2025-01-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleapi', '0003_dungeondata_userid_alter_petitionmanager_dungeon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeondata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
