# Generated by Django 5.1.5 on 2025-01-30 23:37

import puzzleapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleapi', '0004_alter_dungeondata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeondata',
            name='door_pos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dungeondata',
            name='enemy_pos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dungeondata',
            name='player_pos',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='datapetition',
            name='max_moves',
            field=models.IntegerField(default=12, validators=[puzzleapi.validators.validate_max_moves]),
        ),
        migrations.AlterField(
            model_name='datapetition',
            name='mutation_factor',
            field=models.FloatField(default=0.5, validators=[puzzleapi.validators.validate_mutation_factor]),
        ),
    ]
